
// Auto-generated by AutoPilot on 29-07-2023 at 02:28:02

const express = require('express');
const router = express.Router();

// Route to get the 5 highest goal scorer of the last world cup
router.get('/goals', (req, res) => {
    // Data of the 5 highest goal scorer of the last world cup
    let topScorers = [
        { name: 'Harry Kane', goals: 6 },
        { name: 'Antoine Griezmann', goals: 4 },
        { name: 'Romelu Lukaku', goals: 4 },
        { name: 'Cristiano Ronaldo', goals: 4 },
        { name: 'Denis Cheryshev', goals: 4 }
    ];
    res.json(topScorers);
});

module.exports = router;